name: Playwright Tests
on:
  push:
    branches: ["main", "feature/addTests"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Create .env
        run: |
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo NUXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NUXT_PUBLIC_GOOGLE_CLIENT_ID }} >> .env
          echo NUXT_PUBLIC_API_BASE=${{ secrets.NUXT_PUBLIC_API_BASE }} >> .env
          echo NUXT_PUBLIC_NEWEBPAY_FORM_ACTION = ${{ secrets.NUXT_PUBLIC_NEWEBPAY_FORM_ACTION }} >> .env
          echo NUXT_PUBLIC_NEWEBPAY_MERCHANT_ID = ${{ secrets.NUXT_PUBLIC_NEWEBPAY_MERCHANT_ID }} >> .env
          echo NUXT_PUBLIC_NEWEBPAY_VERSION = ${{ secrets.NUXT_PUBLIC_NEWEBPAY_VERSION }}
          cat .env
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30